# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ListaTelefonica' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 3.4'
    pod 'Gloss', '~> 0.7'
    pod 'SDWebImage', '~>3.8'
end
